apiVersion: v1
kind: Secret
metadata:
  name: vm-cloud-init
  namespace: {{ .Release.Namespace }}
stringData:
  userdata: |
    #cloud-config
    user: {{ .Values.secrets.cloudUser }}
    password: redhat
    chpasswd: { expire: False }
    ssh_authorized_keys:
      - {{ .Values.secrets.sshPublicKey }}
