apiVersion: v1
kind: Service
metadata:
  name: centos-vm-lb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: centos-vm-app
    kubevirt.io/domain: centos-vm-{{ .Values.traffic.activeSlot }}
  type: ClusterIP
