apiVersion: v1
kind: Service
metadata:
  name: centos-vm-green-http
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    kubevirt.io/domain: {{ .Values.green.name }}
  type: ClusterIP
