apiVersion: v1
kind: Service
metadata:
  name: centos-vm-green-ssh
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
  selector:
    kubevirt.io/domain: {{ .Values.green.name }}
  type: ClusterIP
