apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: {{ .Values.trident.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  includedNamespaces:
    - namespace: {{ .Release.Namespace }}
