{{- if .Values.blue.enabled }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.blue.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.blue.app }}
    slot: blue
spec:
  runStrategy: {{ .Values.blue.runStrategy }}
  dataVolumeTemplates:
    - metadata:
        name: {{ .Values.blue.name }}-disk
      spec:
        storage:
          accessModes:
            - {{ .Values.storage.accessMode }}
          volumeMode: {{ .Values.storage.volumeMode }}
          resources:
            requests:
              storage: {{ .Values.storage.size }}
          storageClassName: {{ .Values.storage.storageClass }}
        source:
          snapshot:
            name: {{ .Values.blue.sourceSnapshot }}
            namespace: {{ .Values.blue.sourceSnapshotNamespace }}
  template:
    metadata:
      labels:
        app: {{ .Values.blue.app }}
        kubevirt.io/domain: {{ .Values.blue.name }}
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
        cpu:
          cores: 2
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: {{ .Values.blue.name }}-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: vm-cloud-init
{{- end }}
