apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trident-dr-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/cldmnky/rh-demos
    targetRevision: main
    path: gitops-trident-protect-dr-demo/chart
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vm-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: kubevirt.io
      kind: VirtualMachine
      jsonPointers:
        - /spec/template/spec/architecture
        - /spec/dataVolumeTemplates/0/spec/storage/volumeMode
    - group: ""
      kind: Secret
      name: vm-ssh-key
      jsonPointers:
        - /data
