apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-demo
  namespace: vm-demo
spec:
  project: vm-demo
  source:
    repoURL: https://github.com/cldmnky/rh-demos
    targetRevision: main
    path: gitops-vmware-virt-demo/chart
    helm:
      valueFiles:
        - values.yaml
        - values-rosa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vm-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: kubevirt.io
      kind: VirtualMachine
      jsonPointers:
        - /spec/template/spec/architecture
        - /spec/dataVolumeTemplates/0/spec/storage/volumeMode
