# Production environment values (vm-prod)
blue:
  enabled: true
  runStrategy: Always

green:
  enabled: false
  runStrategy: Halted

traffic:
  activeSlot: blue

storage:
  storageClass: storage-class-iscsi
  accessMode: ReadWriteMany
  volumeMode: Block
  size: 30Gi

trident:
  appName: centos-vm-app
  amr:
    enabled: false
