# Default values for trident-dr-demo

secrets:
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA3lypjGQi2L3rT3QbnlqD/dPWQwwQosRVIdmk/pTuEs mbengtss@mbengtss1-mac"
  cloudUser: cloud-user

blue:
  enabled: true
  name: centos-vm-blue
  app: centos-vm-app
  runStrategy: Always
  sourceSnapshot: centos-stream10-bc3fd60ed98e
  sourceSnapshotNamespace: openshift-virtualization-os-images

green:
  enabled: true
  name: centos-vm-green
  app: centos-vm-app
  runStrategy: Halted
  sourceSnapshot: centos-stream10-bc3fd60ed98e
  sourceSnapshotNamespace: openshift-virtualization-os-images

traffic:
  activeSlot: blue

storage:
  storageClass: storage-class-iscsi
  accessMode: ReadWriteMany
  volumeMode: Block
  size: 30Gi

trident:
  appName: centos-vm-app
  amr:
    enabled: false
    name: vm-mirror-relationship
    desiredState: Established
    sourceAppVault: lab-vault
    destinationAppVault: lab-vault
    sourceAppName: centos-vm-app
    sourceAppUID: "" # Set at runtime
    sourceNamespace: vm-prod
    recurrenceRule: |-
      DTSTART:20260101T000000Z
      RRULE:FREQ=MINUTELY;INTERVAL=5
