apiVersion: v1
kind: Pod
metadata:
  name: vm-b
  namespace: vm-workloads
spec:
  containers:
  - name: netexec
    image: registry.k8s.io/e2e-test-images/agnhost:2.45
    command: ["sleep", "infinity"]
  nodeSelector:
    kubernetes.io/hostname: evpn-cluster2-worker
