apiVersion: v1
kind: Service
metadata:
  name: demo-vm-green-http
  namespace: vm-demo
spec:
  selector:
    kubevirt.io/domain: demo-vm-green
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
