apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm-blue
  namespace: vm-demo
  labels:
    app: demo-app
    slot: blue
spec:
  runStrategy: {{ .Values.blue.runStrategy }}
  dataVolumeTemplates:
    - metadata:
        name: centos10-blue
      spec:
        storage:
          accessModes:
            - {{ .Values.storage.accessMode }}
{{- if .Values.storage.volumeMode }}
          volumeMode: {{ .Values.storage.volumeMode }}
{{- end }}
          resources:
            requests:
              storage: {{ .Values.storage.size }}
          storageClassName: {{ .Values.storage.storageClass }}
        source:
          snapshot:
            name: {{ .Values.blue.diskSnapshot.name }}
            namespace: {{ .Values.blue.diskSnapshot.namespace }}
  template:
    metadata:
      labels:
        app: demo-app
        kubevirt.io/domain: demo-vm-blue
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
        cpu:
          cores: 2
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: centos10-blue
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: vm-cloud-init
