apiVersion: v1
kind: Service
metadata:
  name: demo-app-lb
  namespace: vm-demo
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: demo-vm-blue
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
