apiVersion: v1
kind: Service
metadata:
  name: demo-vm-green-ssh
  namespace: vm-demo
spec:
  type: ClusterIP
  selector:
    kubevirt.io/domain: demo-vm-green
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
