apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: upgrade-app-
  namespace: vm-demo
spec:
  pipelineRef:
    name: upgrade-app
  params:
    - name: lb-ip-url
      value: http://demo-app-lb.vm-demo.svc.cluster.local
  workspaces:
    - name: ssh-key
      secret:
        secretName: vm-ssh-key
